{
 "title": "Custom Java Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Money Received(Graph)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    { "expr": "amount_of_money_total", "legendFormat": "Amount of Money Earned" }
   ]
  },
  {
   "title": "Total Money Received(In Dollars)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "amount_of_money_total" }
   ]
  },
  {
   "title": "Total Bookings Made",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "number_of_bookings_total", "legendFormat": "Total Booking Number" }
   ]
  },
  {
   "title": "Total bookings Made",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_bookings_total  " }
   ]
  },
  {
   "title": "Rate of Unstable Transactions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stable_unstable_proportion", "legendFormat": "Unstable rate" }
   ]
  }
 ]
}