apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus-actuator-spring-boot
    run: custom-metric-demo
  name: custom-metric-demo
  namespace: custom-metric-test
spec:
  containers:
  - image: quay.io/zgrinber/custom-metric:2
    imagePullPolicy: IfNotPresent
    name: custom-metric-demo
    ports:
    - containerPort: 8081
      protocol: TCP
      name: http
    - containerPort: 9090
      protocol: TCP
      name: actuator
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  terminationGracePeriodSeconds: 30

