apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus-actuator-spring-boot
  name: custom-metric-demo-spring-actuator
  namespace: custom-metric-test
spec:
  containers:
  - image: quay.io/zgrinber/custom-metric:4
    imagePullPolicy: IfNotPresent
    name: custom-metric-demo
    ports:
    - containerPort: 8081
      protocol: TCP
      name: http
    - containerPort: 9090
      protocol: TCP
      name: actuator
    securityContext:
      capabilities:
        drop:
        - MKNOD
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus-plain-java
  name: custom-metric-demo-plain-java
  namespace: custom-metric-test
spec:
  containers:
    - image: quay.io/zgrinber/custom-metric:JAVA
      imagePullPolicy: IfNotPresent
      name: custom-metric-demo
      ports:
        - containerPort: 8080
          protocol: TCP
          name: http
      securityContext:
        capabilities:
          drop:
            - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  terminationGracePeriodSeconds: 30


