apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-example-monitor
  name: prometheus-example-actuator
  namespace: custom-metric-test
spec:
  endpoints:
    - interval: 15s
      targetPort: actuator
      scheme: http
      path: /actuator/prometheus

  selector:
    matchLabels:
      app: prometheus-actuator-spring-boot
