apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-actuator-spring-boot
  name: custom-metric-demo
  namespace: custom-metric-test
spec:
  clusterIP: 172.30.213.217
  clusterIPs:
  - 172.30.213.217
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: prometheus-actuator-spring-boot
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-actuator-spring-boot
  name: custom-metric-demo-management
  namespace: custom-metric-test
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: actuator
  selector:
    app: prometheus-actuator-spring-boot
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-plain-java
  name: custom-metric-demo-plain-java
  namespace: custom-metric-test
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: prometheus-plain-java
  sessionAffinity: None
  type: ClusterIP


