apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./addition
- ../grafana-operator  

patches:
- path: patch-catalog-source.yaml
  target:
    group: operators.coreos.com
    version: v1alpha1
    kind: CatalogSource

- patch: |-
    - op: replace
      path: /spec/source
      value: old-community-catalog
  target:
    group: operators.coreos.com
    version: v1alpha1
    kind: Subscription
    
