apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: old-community-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  secrets:
    - 11009103-zvi-pull-secret       
  image: registry.redhat.io/redhat/community-operator-index:v4.8
  displayName: Community Operator Catalog old
  publisher: RedHat
  updateStrategy:
    registryPoll:
      interval: 30m

